# Prometheus Configuration for RAGSearch1

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ragsearch1'
    environment: 'production'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # RAGSearch1 API metrics
  - job_name: 'ragsearch1-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL metrics (requires postgres_exporter)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis metrics (requires redis_exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # ChromaDB metrics
  # - job_name: 'chromadb'
  #   static_configs:
  #     - targets: ['chromadb:8000']
  #   metrics_path: '/metrics'
