import { Country, RemittanceService } from "@/types";

// ============================================
// TODOS LOS PAÍSES LATINOAMERICANOS
// ============================================
export const COUNTRIES: Country[] = [
  // USA
  { code: "US", name: "Estados Unidos", currency: "USD", flag: "🇺🇸", active: true, region: 'north-america', currencySymbol: '$' },

  // América Central
  { code: "MX", name: "México", currency: "MXN", flag: "🇲🇽", active: true, region: 'central-america', currencySymbol: '$' },
  { code: "GT", name: "Guatemala", currency: "GTQ", flag: "🇬🇹", active: true, region: 'central-america', currencySymbol: 'Q' },
  { code: "HN", name: "Honduras", currency: "HNL", flag: "🇭🇳", active: true, region: 'central-america', currencySymbol: 'L' },
  { code: "SV", name: "El Salvador", currency: "USD", flag: "🇸🇻", active: true, region: 'central-america', currencySymbol: '$' },
  { code: "NI", name: "Nicaragua", currency: "NIO", flag: "🇳🇮", active: true, region: 'central-america', currencySymbol: 'C$' },
  { code: "CR", name: "Costa Rica", currency: "CRC", flag: "🇨🇷", active: true, region: 'central-america', currencySymbol: '₡' },
  { code: "PA", name: "Panamá", currency: "PAB", flag: "🇵🇦", active: true, region: 'central-america', currencySymbol: 'B/.' },

  // América del Sur
  { code: "CO", name: "Colombia", currency: "COP", flag: "🇨🇴", active: true, region: 'south-america', currencySymbol: '$' },
  { code: "VE", name: "Venezuela", currency: "VES", flag: "🇻🇪", active: true, region: 'south-america', currencySymbol: 'Bs.' },
  { code: "EC", name: "Ecuador", currency: "USD", flag: "🇪🇨", active: true, region: 'south-america', currencySymbol: '$' },
  { code: "PE", name: "Perú", currency: "PEN", flag: "🇵🇪", active: true, region: 'south-america', currencySymbol: 'S/' },
  { code: "BO", name: "Bolivia", currency: "BOB", flag: "🇧🇴", active: true, region: 'south-america', currencySymbol: 'Bs' },
  { code: "CL", name: "Chile", currency: "CLP", flag: "🇨🇱", active: true, region: 'south-america', currencySymbol: '$' },
  { code: "AR", name: "Argentina", currency: "ARS", flag: "🇦🇷", active: true, region: 'south-america', currencySymbol: '$' },
  { code: "UY", name: "Uruguay", currency: "UYU", flag: "🇺🇾", active: true, region: 'south-america', currencySymbol: '$' },
  { code: "PY", name: "Paraguay", currency: "PYG", flag: "🇵🇾", active: true, region: 'south-america', currencySymbol: '₲' },
  { code: "BR", name: "Brasil", currency: "BRL", flag: "🇧🇷", active: true, region: 'south-america', currencySymbol: 'R$' },

  // Caribe
  { code: "DO", name: "República Dominicana", currency: "DOP", flag: "🇩🇴", active: true, region: 'caribbean', currencySymbol: 'RD$' },
  { code: "CU", name: "Cuba", currency: "CUP", flag: "🇨🇺", active: true, region: 'caribbean', currencySymbol: '$' },
  { code: "PR", name: "Puerto Rico", currency: "USD", flag: "🇵🇷", active: true, region: 'caribbean', currencySymbol: '$' },
  { code: "HT", name: "Haití", currency: "HTG", flag: "🇭🇹", active: true, region: 'caribbean', currencySymbol: 'G' },
];

// ============================================
// TODOS LOS PROVEEDORES DE REMESAS
// ============================================
export const REMITTANCE_SERVICES: RemittanceService[] = [
  // PLATAFORMAS DIGITALES INTERNACIONALES
  {
    id: "wise",
    name: "Wise",
    icon: "💚",
    commission: 0.5,
    timeMin: 60,
    timeMax: 180,
    rate: 0,
    recommended: true,
    type: 'digital',
    paymentMethods: ['Tarjeta', 'Transferencia bancaria', 'Débito directo'],
    deliveryMethods: ['Cuenta bancaria'],
    minAmount: 1,
    maxAmount: 1000000,
    countries: ['MX', 'CO', 'AR', 'BR', 'PE', 'CL', 'EC', 'UY'],
    rating: 4.8,
    url: 'https://wise.com',
    speed: 'same-day'
  },
  {
    id: "remitly",
    name: "Remitly",
    icon: "💙",
    commission: 0,
    timeMin: 15,
    timeMax: 60,
    rate: 0,
    recommended: true,
    type: 'digital',
    paymentMethods: ['Tarjeta débito', 'Tarjeta crédito', 'Transferencia'],
    deliveryMethods: ['Cuenta bancaria', 'Efectivo', 'Domicilio'],
    minAmount: 10,
    maxAmount: 30000,
    countries: ['MX', 'GT', 'HN', 'SV', 'NI', 'CR', 'PA', 'CO', 'VE', 'EC', 'PE', 'BO', 'CL', 'AR', 'UY', 'PY', 'BR', 'DO', 'HT'],
    rating: 4.7,
    url: 'https://remitly.com',
    speed: 'instant'
  },
  {
    id: "western-union",
    name: "Western Union",
    icon: "💛",
    commission: 5,
    timeMin: 5,
    timeMax: 15,
    rate: 0,
    recommended: false,
    type: 'traditional',
    paymentMethods: ['Efectivo', 'Tarjeta', 'Transferencia', 'Débito'],
    deliveryMethods: ['Efectivo', 'Cuenta bancaria', 'Billetera móvil'],
    minAmount: 10,
    maxAmount: 10000,
    countries: ['MX', 'GT', 'HN', 'SV', 'NI', 'CR', 'PA', 'CO', 'VE', 'EC', 'PE', 'BO', 'CL', 'AR', 'UY', 'PY', 'BR', 'DO', 'CU', 'PR', 'HT'],
    rating: 4.2,
    url: 'https://westernunion.com',
    speed: 'instant'
  },
  {
    id: "moneygram",
    name: "MoneyGram",
    icon: "🟠",
    commission: 4.5,
    timeMin: 10,
    timeMax: 30,
    rate: 0,
    recommended: false,
    type: 'traditional',
    paymentMethods: ['Efectivo', 'Tarjeta', 'Transferencia bancaria'],
    deliveryMethods: ['Efectivo', 'Cuenta bancaria', 'Domicilio'],
    minAmount: 1,
    maxAmount: 10000,
    countries: ['MX', 'GT', 'HN', 'SV', 'NI', 'CR', 'PA', 'CO', 'VE', 'EC', 'PE', 'BO', 'CL', 'AR', 'UY', 'PY', 'BR', 'DO', 'HT'],
    rating: 4.1,
    url: 'https://moneygram.com',
    speed: 'instant'
  },
  {
    id: "xoom",
    name: "Xoom (PayPal)",
    icon: "💜",
    commission: 0,
    timeMin: 30,
    timeMax: 120,
    rate: 0,
    recommended: true,
    type: 'digital',
    paymentMethods: ['PayPal', 'Tarjeta', 'Cuenta bancaria'],
    deliveryMethods: ['Cuenta bancaria', 'Efectivo', 'Domicilio'],
    minAmount: 10,
    maxAmount: 10000,
    countries: ['MX', 'GT', 'HN', 'SV', 'NI', 'CR', 'PA', 'CO', 'EC', 'PE', 'CL', 'AR', 'BR', 'DO'],
    rating: 4.5,
    url: 'https://xoom.com',
    speed: 'same-day'
  },
  {
    id: "worldremit",
    name: "WorldRemit",
    icon: "🌐",
    commission: 3.99,
    timeMin: 15,
    timeMax: 60,
    rate: 0,
    recommended: false,
    type: 'digital',
    paymentMethods: ['Tarjeta', 'Transferencia', 'Apple Pay', 'Google Pay'],
    deliveryMethods: ['Cuenta bancaria', 'Efectivo', 'Billetera móvil'],
    minAmount: 1,
    maxAmount: 9000,
    countries: ['MX', 'CO', 'PE', 'CL', 'AR', 'BR', 'DO'],
    rating: 4.3,
    url: 'https://worldremit.com',
    speed: 'instant'
  },
  {
    id: "ria",
    name: "Ria Money Transfer",
    icon: "🔴",
    commission: 3,
    timeMin: 15,
    timeMax: 45,
    rate: 0,
    recommended: false,
    type: 'traditional',
    paymentMethods: ['Efectivo', 'Tarjeta', 'Transferencia'],
    deliveryMethods: ['Efectivo', 'Cuenta bancaria', 'Domicilio'],
    minAmount: 1,
    maxAmount: 7499,
    countries: ['MX', 'GT', 'HN', 'SV', 'NI', 'CR', 'PA', 'CO', 'EC', 'PE', 'BO', 'CL', 'AR', 'UY', 'PY', 'BR', 'DO', 'CU'],
    rating: 4.0,
    url: 'https://riamoneytransfer.com',
    speed: 'instant'
  },
  {
    id: "smallworld",
    name: "Small World",
    icon: "🌍",
    commission: 0,
    timeMin: 30,
    timeMax: 120,
    rate: 0,
    recommended: false,
    type: 'digital',
    paymentMethods: ['Tarjeta', 'Transferencia'],
    deliveryMethods: ['Cuenta bancaria', 'Efectivo'],
    minAmount: 10,
    maxAmount: 5000,
    countries: ['MX', 'CO', 'EC', 'PE', 'CL', 'AR', 'BR'],
    rating: 4.2,
    url: 'https://smallworldfs.com',
    speed: 'same-day'
  },
  {
    id: "pangea",
    name: "Pangea Money Transfer",
    icon: "📱",
    commission: 0,
    timeMin: 15,
    timeMax: 60,
    rate: 0,
    recommended: false,
    type: 'digital',
    paymentMethods: ['Tarjeta débito', 'Cuenta bancaria'],
    deliveryMethods: ['Cuenta bancaria', 'Efectivo'],
    minAmount: 10,
    maxAmount: 2999,
    countries: ['MX', 'GT', 'HN', 'SV', 'NI', 'CO', 'EC', 'PE', 'BR', 'DO'],
    rating: 4.4,
    url: 'https://gopangea.com',
    speed: 'same-day'
  },
  {
    id: "sendwave",
    name: "Sendwave",
    icon: "🚀",
    commission: 0,
    timeMin: 10,
    timeMax: 30,
    rate: 0,
    recommended: false,
    type: 'digital',
    paymentMethods: ['Tarjeta débito'],
    deliveryMethods: ['Billetera móvil', 'Efectivo'],
    minAmount: 10,
    maxAmount: 1000,
    countries: ['MX', 'GT', 'HN', 'SV'],
    rating: 4.6,
    url: 'https://sendwave.com',
    speed: 'instant'
  },

  // EXCHANGES DE CRIPTOMONEDAS
  {
    id: "binance",
    name: "Binance P2P",
    icon: "₿",
    commission: 0,
    timeMin: 15,
    timeMax: 45,
    rate: 0,
    recommended: true,
    type: 'crypto',
    paymentMethods: ['Transferencia', 'Pago móvil', 'Efectivo'],
    deliveryMethods: ['USDT', 'Cuenta bancaria', 'Pago móvil'],
    minAmount: 10,
    maxAmount: 50000,
    countries: ['MX', 'CO', 'VE', 'AR', 'BR', 'PE', 'CL'],
    rating: 4.5,
    url: 'https://binance.com/p2p',
    speed: 'instant'
  },
  {
    id: "bitso",
    name: "Bitso",
    icon: "🟢",
    commission: 1,
    timeMin: 5,
    timeMax: 30,
    rate: 0,
    recommended: true,
    type: 'crypto',
    paymentMethods: ['SPEI', 'Tarjeta', 'Transferencia'],
    deliveryMethods: ['Cuenta bancaria', 'Cripto wallet'],
    minAmount: 50,
    maxAmount: 100000,
    countries: ['MX', 'CO', 'AR'],
    rating: 4.7,
    url: 'https://bitso.com',
    speed: 'instant'
  },
  {
    id: "ripio",
    name: "Ripio",
    icon: "🟣",
    commission: 0.5,
    timeMin: 10,
    timeMax: 30,
    rate: 0,
    recommended: false,
    type: 'crypto',
    paymentMethods: ['Transferencia', 'Efectivo'],
    deliveryMethods: ['Cuenta bancaria', 'Cripto wallet'],
    minAmount: 100,
    maxAmount: 50000,
    countries: ['AR', 'BR', 'MX', 'CO', 'UY'],
    rating: 4.3,
    url: 'https://ripio.com',
    speed: 'same-day'
  },
  {
    id: "airtm",
    name: "AirTM",
    icon: "🌐",
    commission: 2.99,
    timeMin: 30,
    timeMax: 60,
    rate: 0,
    recommended: false,
    type: 'crypto',
    paymentMethods: ['Transferencia', 'PayPal', 'Cripto', 'Zelle'],
    deliveryMethods: ['Cuenta bancaria', 'PayPal', 'Pago móvil', 'Efectivo'],
    minAmount: 5,
    maxAmount: 2500,
    countries: ['MX', 'CO', 'VE', 'EC', 'PE', 'BO', 'CL', 'AR', 'UY', 'PY', 'BR'],
    rating: 4.0,
    url: 'https://airtm.com',
    speed: 'same-day'
  },
  {
    id: "reserve",
    name: "Reserve",
    icon: "🔵",
    commission: 1.5,
    timeMin: 5,
    timeMax: 15,
    rate: 0,
    recommended: true,
    type: 'crypto',
    paymentMethods: ['Cripto', 'Zelle', 'Transferencia'],
    deliveryMethods: ['Reserve app', 'Pago móvil', 'Transferencia'],
    minAmount: 1,
    maxAmount: 10000,
    countries: ['VE', 'AR', 'CO'],
    rating: 4.6,
    url: 'https://reserve.org',
    speed: 'instant'
  },
  {
    id: "localbitcoins",
    name: "LocalBitcoins",
    icon: "🪙",
    commission: 1,
    timeMin: 30,
    timeMax: 120,
    rate: 0,
    recommended: false,
    type: 'crypto',
    paymentMethods: ['Transferencia', 'Efectivo', 'PayPal'],
    deliveryMethods: ['Bitcoin wallet', 'Cuenta bancaria'],
    minAmount: 10,
    maxAmount: 25000,
    countries: ['MX', 'CO', 'VE', 'AR', 'BR', 'PE', 'CL'],
    rating: 3.9,
    url: 'https://localbitcoins.com',
    speed: '1-3-days'
  },

  // FINTECHS LOCALES
  {
    id: "nequi",
    name: "Nequi (Colombia)",
    icon: "🇨🇴",
    commission: 0,
    timeMin: 1,
    timeMax: 5,
    rate: 0,
    recommended: true,
    type: 'fintech',
    paymentMethods: ['Cuenta Nequi', 'Tarjeta'],
    deliveryMethods: ['Cuenta Nequi'],
    minAmount: 1000,
    maxAmount: 10000000,
    countries: ['CO'],
    rating: 4.8,
    url: 'https://nequi.com.co',
    speed: 'instant'
  },
  {
    id: "mercadopago",
    name: "Mercado Pago",
    icon: "💙",
    commission: 0,
    timeMin: 1,
    timeMax: 10,
    rate: 0,
    recommended: true,
    type: 'fintech',
    paymentMethods: ['Saldo MP', 'Tarjeta', 'Transferencia'],
    deliveryMethods: ['Cuenta MP', 'Cuenta bancaria'],
    minAmount: 1,
    maxAmount: 100000,
    countries: ['MX', 'AR', 'BR', 'CL', 'CO', 'UY', 'PE'],
    rating: 4.7,
    url: 'https://mercadopago.com',
    speed: 'instant'
  },
  {
    id: "rappi",
    name: "RappiPay",
    icon: "🧡",
    commission: 0,
    timeMin: 1,
    timeMax: 10,
    rate: 0,
    recommended: false,
    type: 'fintech',
    paymentMethods: ['Saldo Rappi', 'Tarjeta'],
    deliveryMethods: ['Cuenta Rappi'],
    minAmount: 1000,
    maxAmount: 5000000,
    countries: ['CO', 'MX', 'AR', 'BR', 'CL', 'PE', 'UY'],
    rating: 4.4,
    url: 'https://rappi.com',
    speed: 'instant'
  },
  {
    id: "nubank",
    name: "Nubank",
    icon: "💜",
    commission: 0,
    timeMin: 5,
    timeMax: 30,
    rate: 0,
    recommended: true,
    type: 'fintech',
    paymentMethods: ['Cuenta Nu', 'Tarjeta Nu'],
    deliveryMethods: ['Cuenta Nu'],
    minAmount: 1,
    maxAmount: 50000,
    countries: ['BR', 'MX', 'CO'],
    rating: 4.9,
    url: 'https://nubank.com.br',
    speed: 'instant'
  },
];

export const RATE_SOURCES = {
  BCV: "bcv",
  PARALELO: "paralelo",
  BINANCE: "binance",
} as const;

// Tipos de servicios para filtros
export const SERVICE_TYPES = [
  { id: 'all', label: 'Todos', icon: '🌐' },
  { id: 'digital', label: 'Plataformas Digitales', icon: '📱' },
  { id: 'crypto', label: 'Criptomonedas', icon: '₿' },
  { id: 'traditional', label: 'Tradicionales', icon: '🏢' },
  { id: 'fintech', label: 'Fintech', icon: '💳' },
  { id: 'bank', label: 'Bancos', icon: '🏛️' },
] as const;

// Velocidades de entrega para filtros
export const DELIVERY_SPEEDS = [
  { id: 'all', label: 'Todas', icon: '⏱️' },
  { id: 'instant', label: 'Instantáneo', icon: '⚡' },
  { id: 'same-day', label: 'Mismo día', icon: '📅' },
  { id: '1-3-days', label: '1-3 días', icon: '📆' },
  { id: '3-7-days', label: '3-7 días', icon: '📋' },
] as const;

// Ordenamiento para tabla comparativa
export const SORT_OPTIONS = [
  { id: 'rate', label: 'Mejor tipo de cambio', icon: '💱' },
  { id: 'commission', label: 'Menor comisión', icon: '💰' },
  { id: 'speed', label: 'Más rápido', icon: '⚡' },
  { id: 'rating', label: 'Mejor calificación', icon: '⭐' },
  { id: 'total', label: 'Mayor cantidad neta', icon: '💵' },
] as const;
